# Generated by Django 5.1.15 on 2026-08-04 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('repo_url', models.URLField(blank=True)),
                ('stack', models.CharField(blank=True, max_length=200)),
                ('build_command', models.CharField(blank=True, max_length=500)),
                ('test_command', models.CharField(blank=True, max_length=500)),
                ('lint_command', models.CharField(blank=True, max_length=500)),
                ('default_model', models.CharField(choices=[('haiku', 'Haiku'), ('sonnet', 'Sonnet'), ('opus', 'Opus'), ('auto', 'Automático (por complexidade)')], default='auto', max_length=20)),
                ('priority_weight', models.PositiveSmallIntegerField(default=1)),
                ('agent_permissions', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-priority_weight', 'name'],
            },
        ),
    ]
