# Generated by Django 5.1.15 on 2026-08-04 23:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatusSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch', models.CharField(blank=True, max_length=255)),
                ('ahead', models.IntegerField(default=0)),
                ('behind', models.IntegerField(default=0)),
                ('open_prs', models.IntegerField(default=0)),
                ('ci_status', models.CharField(blank=True, max_length=50)),
                ('last_commit', models.CharField(blank=True, max_length=500)),
                ('changed_files', models.IntegerField(default=0)),
                ('state', models.CharField(choices=[('precisa_de_voce', 'Precisa de você'), ('rodando', 'Rodando'), ('em_dia', 'Em dia'), ('parado', 'Parado')], default='parado', max_length=20)),
                ('summary', models.CharField(blank=True, max_length=280)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='projects.project')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['project', '-created_at'], name='status_stat_project_d9663d_idx')],
            },
        ),
    ]
