# Generated by Django 5.1.15 on 2026-08-06 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='statussnapshot',
            name='checks',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='statussnapshot',
            name='coverage_pct',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
