# Generated by Django 5.1.15 on 2026-08-04 23:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instruction', models.TextField()),
                ('urgency', models.CharField(choices=[('now', 'Agora'), ('nightly', 'Fila noturna')], default='now', max_length=10)),
                ('state', models.CharField(choices=[('queued', 'Na fila'), ('running', 'Rodando'), ('needs_review', 'Precisa de revisão'), ('done', 'Concluída'), ('failed', 'Falhou')], default='queued', max_length=15)),
                ('model_used', models.CharField(blank=True, max_length=20)),
                ('summary', models.CharField(blank=True, max_length=280)),
                ('pr_url', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_runs', to='projects.project')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
