# Generated by Django 5.1.15 on 2026-08-05 19:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskrun',
            name='adjustment_instructions',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='taskrun',
            name='base_branch',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='taskrun',
            name='branch_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='taskrun',
            name='consecutive_verify_failures',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='taskrun',
            name='state',
            field=models.CharField(choices=[('queued', 'Na fila'), ('running', 'Rodando'), ('needs_review', 'Precisa de revisão'), ('done', 'Concluída'), ('failed', 'Falhou'), ('discarded', 'Descartada')], default='queued', max_length=15),
        ),
        migrations.CreateModel(
            name='TaskRunStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phase', models.CharField(choices=[('discuss', 'Discuss'), ('plan', 'Plan'), ('execute', 'Execute'), ('verify', 'Verify'), ('ship', 'Ship')], max_length=10)),
                ('attempt', models.PositiveSmallIntegerField(default=1)),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('running', 'Rodando'), ('done', 'Concluído'), ('failed', 'Falhou'), ('skipped', 'Pulado')], default='pending', max_length=10)),
                ('model_used', models.CharField(blank=True, max_length=20)),
                ('detail', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('task_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='agents.taskrun')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
