# Generated by Django 5.1.15 on 2026-08-05 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0002_taskrun_adjustment_instructions_taskrun_base_branch_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskrunstep',
            name='cost_usd',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True),
        ),
    ]
