# Generated by Django 5.1.15 on 2026-08-06 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0003_taskrunstep_cost_usd'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskrun',
            name='model_override',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
