# Generated by Django 5.1.15 on 2026-08-06 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0004_taskrun_model_override'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskrunstep',
            name='cache_read_tokens',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='taskrunstep',
            name='cache_write_tokens',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
