# Generated by Django 5.1.15 on 2026-08-04 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetWindow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start', models.DateField(unique=True)),
                ('quota_total', models.BigIntegerField(default=0)),
                ('used', models.BigIntegerField(default=0)),
                ('personal_reserve', models.BigIntegerField(default=0)),
                ('pause_threshold_pct', models.PositiveSmallIntegerField(default=85)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-week_start'],
            },
        ),
    ]
