# Generated by Django 5.1.15 on 2026-08-05 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quota_total_usd', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('personal_reserve_pct', models.PositiveSmallIntegerField(default=15)),
                ('pause_threshold_pct', models.PositiveSmallIntegerField(default=85)),
                ('reset_weekday', models.PositiveSmallIntegerField(default=1)),
                ('reset_hour', models.PositiveSmallIntegerField(default=9)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name='BudgetWindow',
        ),
    ]
